/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.frar.jjjrmi;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Logger;
import org.apache.logging.log4j.Level;

/**
 *
 * @author Ed Armstrong
 */
public class Global {
    final public static org.apache.logging.log4j.Logger LOGGER = org.apache.logging.log4j.LogManager.getLogger("JJJRMI");
    final public static Level VERBOSE = Level.forName("VERBOSE", 450);
    final public static Level VERY_VERBOSE = Level.forName("VERY_VERBOSE", 450);
    public static String FILE_STAMP;
    
    static{
        try {
            InputStream stream = Global.class.getClassLoader().getResourceAsStream("project.properties");
            Properties properties = new Properties();
            properties.load(stream);
            FILE_STAMP = String.format("// Generated by JJJRMI %s\n", properties.get("version"));
        } catch (IOException ex) {
            Logger.getLogger(Global.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
}
