/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.frar.jjjrmi;
import org.apache.logging.log4j.Level;

/**
 *
 * @author Ed Armstrong
 */
public class Global {
    final public static org.apache.logging.log4j.Logger LOGGER = org.apache.logging.log4j.LogManager.getLogger("JJJRMI");
    final public static Level VERBOSE = Level.forName("VERBOSE", 450);
    final public static Level VERY_VERBOSE = Level.forName("VERY_VERBOSE", 450);
    final public static String FILE_STAMP = "// Generated by JJJRMI 0.6.4\n";
}
