"use strict";
class ArrayList {
    constructor() {
        this.list = [];
    }
    
    getItem(index){
        return this.list[index];
    }
};

if (typeof module !== "undefined") module.exports = ArrayList;
// Generated by JJJRMI 0.6.3
// 20.02.28 17:18:51
