"use strict";
const Shapes = require("./Shapes");
class ArrayWrapper {
	constructor() {
            this.arrayField1 = [1, 1, 2, 3, 5];
            this.arrayField2 = new Array(5);
            this.arrayField3 = [Shapes.CIRCLE, Shapes.SQUARE, Shapes.SQUARE, Shapes.TRIANGLE];
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.ArrayWrapper";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = ArrayWrapper;
// Generated by JJJRMI 0.6.3
// 20.02.17 18:46:00
