"use strict";
const Shapes = require("./Shapes");
class ArrayWrapper {
	constructor() {
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.arrayField1 = new Array(0);
            this.arrayField2 = new Array(5);
            this.arrayField3 = new Array(0);
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.ArrayWrapper";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = ArrayWrapper;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
