"use strict";
class CircularRef {
	constructor(target = new CircularRef(this)) {
            this.__init();
            this.target = target;
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.target = undefined;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.CircularRef";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = CircularRef;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
