"use strict";
class CircularRef {
	constructor(target = new CircularRef(this)) {
            /* no super class */;
            this.target = target;
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.CircularRef";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = CircularRef;
// Generated by JJJRMI 0.6.3
// 20.02.17 15:45:03
