"use strict";
class Constants {
	constructor() {
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {}
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Constants";
        }
	static __isHandler() {
            return false;
        }
};
Constants.GLOBAL = "ima global";

if (typeof module !== "undefined") module.exports = Constants;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
