"use strict";
class DoNotRetainExtends {
	constructor() {
            this.__init();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.DoNotRetainExtends";
        }
	static __isEnum() {
            return false;
        }
	__init() {
            this.x = 0;
        }
	getX() {
            return this.x;
        }
	setX(x) {
            this.x = x;
        }
};

if (typeof module !== "undefined") module.exports = DoNotRetainExtends;
// Generated by JJJRMI 0.6.3
// 20.02.22 21:46:13
