"use strict";
class DoNotRetainAnno {
	constructor(x) {
            this.__init();
            this.x = x;
        }
	getX() {
            return this.x;
        }
	setX(x) {
            this.x = x;
        }
	static __isRetained() {
            return false;
        }
	__init() {
            this.x = 0;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.DoNotRetainAnno";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = DoNotRetainAnno;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
