"use strict";
class EmptyConstructor {
	constructor() {
            /* no super class */;
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.EmptyConstructor";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = EmptyConstructor;
// Generated by JJJRMI 0.6.3
// 20.02.17 15:45:03
