"use strict";
const NoneAnnotated = require("./NoneAnnotated");
class ExtendsNoneAnnotated extends NoneAnnotated {
	constructor() {
            super();
            this.__init();
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.ExtendsNoneAnnotated";
        }
	static __isEnum() {
            return false;
        }
	__init() {}
};

if (typeof module !== "undefined") module.exports = ExtendsNoneAnnotated;
// Generated by JJJRMI 0.6.3
// 20.02.20 13:21:28
