"use strict";
const None = require("./None");
class ExtendsNone extends None {
	constructor() {
            super();
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {}
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.ExtendsNone";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = ExtendsNone;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
