"use strict";
const None = require("./None");
class ExtendsNone extends None {
	constructor() {
            super();
            this.__init();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.ExtendsNone";
        }
	static __isEnum() {
            return false;
        }
	__init() {}
};

if (typeof module !== "undefined") module.exports = ExtendsNone;
// Generated by JJJRMI 0.6.3
// 20.02.21 16:37:39
