"use strict";
const NoneAnnotated = require("./NoneAnnotated");
class ExtendsNoneAnnotated extends NoneAnnotated {
	constructor() {
            super();
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {}
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.ExtendsNoneAnnotated";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = ExtendsNoneAnnotated;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
