"use strict";
class Foo {
	constructor(x) {
            /* no super class */;
            this.x = x;
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Foo";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = Foo;
// Generated by JJJRMI 0.6.3
// 20.02.14 16:37:19
