"use strict";
class GameController {
	constructor() {}
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testable.gamecontroller.GameController";
        }
	static __isEnum() {
            return false;
        }
	getPID() {
            return this.pid;
        }
};

if (typeof module !== "undefined") module.exports = GameController;
// Generated by JJJRMI 0.6.3
// 20.02.17 17:01:27
