"use strict";
class Has {
	constructor(t = undefined) {
            this.__init();
            this.t = t;
        }
	set(t) {
            this.t = t;
        }
	static __isRetained() {
            return true;
        }
	get() {
            return this.t;
        }
	__init() {
            this.t = undefined;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Has";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = Has;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
