"use strict";
class HasHandler {
	constructor(x, y) {
            this.__init();
            this.x = x;
            this.y = y;
            this.z = x * y;
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.x = undefined;
            this.y = undefined;
            this.z = undefined;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.HasHandler";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = HasHandler;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
