"use strict";
class HasHandler {
	constructor(x, y) {
            this.x = x;
            this.y = y;
            this.z = x * y;            
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.HasHandler";
        }
	static __isEnum() {
            return false;
        }
};

require("jjjrmi/translator/HandlerFactory").getInstance().setHandler(HasHandler.__getClass(), require("./IsHandler")); 

if (typeof module !== "undefined") module.exports = HasHandler;
// Generated by JJJRMI 0.6.3
// 20.02.12 11:26:03
