"use strict";
const None = require("./None");
class HasNone {
	constructor() {
            /* no super class */;
            this.none = new None();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.HasNone";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = HasNone;
// Generated by JJJRMI 0.6.3
// 20.02.14 16:37:19
