"use strict";
const None = require("./None");
class HasNone {
	constructor() {
            this.__init();
            this.none = new None();
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.none = undefined;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.HasNone";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = HasNone;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
