"use strict";
class HasStatic {
	constructor() {
            this.__init();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.HasStatic";
        }
	static __isEnum() {
            return false;
        }
	__init() {
            this.iAmNotStatic = 6;
        }
	static iAmMethod() {}
};
HasStatic.iAmInteger = 5;

if (typeof module !== "undefined") module.exports = HasStatic;
// Generated by JJJRMI 0.6.3
// 20.02.20 13:21:28
