"use strict";
const None = require("./None");
class HasSuper1 extends None {
	constructor() {
            super();
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {}
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.HasSuper1";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = HasSuper1;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
