"use strict";
class HasStatic {
	constructor() {
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.iAmNotStatic = 6;
        }
	static __isEnum() {
            return false;
        }
	static iAmMethod() {}
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.HasStatic";
        }
	static __isHandler() {
            return false;
        }
};
HasStatic.iAmInteger = 5;

if (typeof module !== "undefined") module.exports = HasStatic;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
