"use strict";
class InConstructor {
	constructor() {
            this.__init();
            this.a = 'a';
            this.b = String.fromCharCode(66);
            this.c = String.fromCharCode(66);
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.a = undefined;
            this.b = undefined;
            this.c = undefined;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.charcode.InConstructor";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = InConstructor;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
