"use strict";
class Simple {
	constructor() {
            /* no super class */;
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Simple";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = Simple;
// Generated by JJJRMI 0.6.3
// 20.02.17 15:51:44
