"use strict";
const HasHandler = require("./HasHandler");
const Ahandler = require("jjjrmi/translator/Ahandler");

class IsHandler extends Ahandler{
	constructor(encodedResult) {
            super(encodedResult);
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.IsHandler";
        }
	static __handles() {
            return "ca.frar.jjjrmi.testclasses.HasHandler";
        }        
	static __isEnum() {
            return false;
        }
	decode(hasHandler) {
            hasHandler.x = this.decodeField("a");
            hasHandler.y = this.decodeField("b");
            hasHandler.z = hasHandler.x + hasHandler.y;
        }
	encode(object) {
            this.encodeField("a", object.x);
            this.encodeField("b", object.y);
        }
	getInstance() {
            return new HasHandler();
        }
};

if (typeof module !== "undefined") module.exports = IsHandler;
// Generated by JJJRMI 0.6.3
// 20.02.12 11:26:03
