"use strict";
const HasHandler = require("./HasHandler");
class IsHandler {
	constructor() {
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.IsHandler";
        }
	static __isEnum() {
            return false;
        }
	decode(hasHandler) {
            this.decodeField("a", "x");
            this.decodeField("b", "y");
            hasHandler.z = hasHandler.x + hasHandler.y;
        }
	encode(object) {
            this.encodeField("a", object.x);
            this.encodeField("b", object.y);
        }
	getInstance() {
            return new HasHandler();
        }
};

if (typeof module !== "undefined") module.exports = IsHandler;
// Generated by JJJRMI 0.6.3
// 20.02.15 17:18:17
