"use strict";
const Float = require("./Float");
const Integer = require("./Integer");
const HasHandler = require("./HasHandler");
class IsHandler {
	constructor() {
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.IsHandler";
        }
	static __isEnum() {
            return false;
        }
	decode(hasHandler) {
            hasHandler.x = this.decodeField("a", Integer.class);
            hasHandler.y = this.decodeField("b", Float.class);
            hasHandler.z = hasHandler.x + hasHandler.y;
        }
	encode(object) {
            this.encodeField("a", object.x);
            this.encodeField("b", object.y);
        }
	getInstance() {
            return new HasHandler();
        }
};

if (typeof module !== "undefined") module.exports = IsHandler;
// Generated by JJJRMI 0.6.3
// 20.02.14 16:37:19
