"use strict";
const Constants = require("./Constants");
class JJJAnnoHasConstant {
	constructor() {
            this.__init();
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.JJJAnnoHasConstant";
        }
	static __isEnum() {
            return false;
        }
	__init() {
            this.constant = undefined;
        }
	HasConstant() {
            this.constant = Constants.GLOBAL;
        }
};

if (typeof module !== "undefined") module.exports = JJJAnnoHasConstant;
// Generated by JJJRMI 0.6.3
// 20.02.18 14:48:27
