"use strict";
const Constants = require("./Constants");
class JJJObjectHasConstant {
	constructor() {
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.JJJObjectHasConstant";
        }
	static __isEnum() {
            return false;
        }
	HasConstant() {
            this.constant = Constants.GLOBAL;
        }
};

if (typeof module !== "undefined") module.exports = JJJObjectHasConstant;
// Generated by JJJRMI 0.6.3
// 20.02.11 14:18:24
