"use strict";
const Constants = require("./Constants");
class JJJObjectHasConstant {
	constructor() {
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.constant = undefined;
        }
	HasConstant() {
            this.constant = Constants.GLOBAL;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.JJJObjectHasConstant";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = JJJObjectHasConstant;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
