"use strict";
class JSEmptyClassCode {
	constructor() {}
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.JSEmptyClassCode";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = JSEmptyClassCode;
// Generated by JJJRMI 0.6.3
// 20.02.17 17:24:26
