"use strict";
const JSLambdaCode = require("./JSLambdaCode");
class JSInclude {
	constructor() {}
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.JSInclude";
        }
	static __isEnum() {
            return false;
        }
	run() {
            this.callback = new JSLambdaCode();
        }
};

if (typeof module !== "undefined") module.exports = JSInclude;
// Generated by JJJRMI 0.6.3
// 20.02.17 17:01:27
