"use strict";
class JSLambdaCode {
	constructor() {
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {}
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.JSLambdaCode";
        }
	static __isHandler() {
            return false;
        }
	callsLambda2() {
            this.takesLambda((e)=>{
                e = e.concat(" i really am");
                e.toString();
            });
        }
	callsLambda1() {
            this.takesLambda((e)=>e.toString());
        }
	takesLambda(consumer) {
            consumer.accept("ima string");
        }
};

if (typeof module !== "undefined") module.exports = JSLambdaCode;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:12
