"use strict";
class JSLambdaCode {
	constructor() {
            this.__init();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.JSLambdaCode";
        }
	static __isEnum() {
            return false;
        }
	__init() {}
	callsLambda1() {
            this.takesLambda((e)=>e.toString());
        }
	callsLambda2() {
            this.takesLambda((e)=>{
                e = e.concat(" i really am");
                e.toString();
            });
        }
	takesLambda(consumer) {
            consumer.accept("ima string");
        }
};

if (typeof module !== "undefined") module.exports = JSLambdaCode;
// Generated by JJJRMI 0.6.3
// 20.02.20 13:21:27
