"use strict";
class MissingConstructor {
	constructor() {
            this.__init();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.MissingConstructor";
        }
	static __isEnum() {
            return false;
        }
	__init() {}
};

if (typeof module !== "undefined") module.exports = MissingConstructor;
// Generated by JJJRMI 0.6.3
// 20.02.18 15:08:31
