"use strict";
class NoneAnnotated {
	constructor() {
            this.__init();
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.NoneAnnotated";
        }
	static __isEnum() {
            return false;
        }
	__init() {}
};

if (typeof module !== "undefined") module.exports = NoneAnnotated;
// Generated by JJJRMI 0.6.3
// 20.02.25 14:58:22
