"use strict";
class NonEmptyConstructor {
	constructor(x) {
            this.__init();
            this.x = x;
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.x = undefined;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.NonEmptyConstructor";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = NonEmptyConstructor;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
