"use strict";
const NonEmptyConstructor = require("./NonEmptyConstructor");
class NonEmptySuper extends NonEmptyConstructor {
	constructor() {
            super(MyEnum.C);
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.NonEmptySuper";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = NonEmptySuper;
// Generated by JJJRMI 0.6.3
// 20.02.17 17:01:26
