"use strict";
const MyEnum = require("./MyEnum");
const NonEmptyConstructor = require("./NonEmptyConstructor");
class NonEmptySuper extends NonEmptyConstructor {
	constructor() {
            super(MyEnum.C);
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {}
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.NonEmptySuper";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = NonEmptySuper;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
