"use strict";
class NoRetain {
	constructor() {
            this.__init();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.NoRetain";
        }
	static __isEnum() {
            return false;
        }
	__init() {
            this.x = 5;
        }
};

if (typeof module !== "undefined") module.exports = NoRetain;
// Generated by JJJRMI 0.6.3
// 20.02.19 13:19:28
