"use strict";
class NoRetain {
	constructor() {
            this.x = 5;
            
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.NoRetain";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = NoRetain;
// Generated by JJJRMI 0.6.3
// 20.02.17 15:45:02
