"use strict";
class NoRetain {
	constructor() {
            this.__init();
        }
	static __isRetained() {
            return false;
        }
	__init() {
            this.x = 5;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.NoRetain";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = NoRetain;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
