"use strict";
class Primitives {
	constructor(x = 7) {
            this.__init();
            this.string = "alpha" + x;
            this.bt = x % 2 === 0;
            this.bf = !this.bt;
            this.bite = x;
            this.car = x;
            this.shrt = 100 * x;
            this.loooong = 2147483647 * x;
            this.duble = 1.2 * x;
            this.f = 1.2 * x;
            this.i = x;
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Primitives";
        }
	static __isEnum() {
            return false;
        }
	__init() {
            this.string = "alpha";
            this.bt = true;
            this.bf = false;
            this.bite = 7;
            this.car = 'a';
            this.shrt = 100;
            this.loooong = 2147483647 * 10;
            this.duble = 1.2;
            this.f = 1.2;
            this.i = -1;
            this.z = undefined;
        }
};

if (typeof module !== "undefined") module.exports = Primitives;
// Generated by JJJRMI 0.6.3
// 20.02.18 14:52:42
