"use strict";
class Primitives {
	constructor() {
            this.string = "alpha";
            this.bt = true;
            this.bf = false;
            this.bite = 7;
            this.car = 'a';
            this.shrt = 100;
            this.loooong = Integer.MAX_VALUE * 10;
            this.duble = 1.2;
            this.f = 1.2;
            this.i = -1;
            
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Primitives";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = Primitives;
// Generated by JJJRMI 0.6.3
// 20.02.11 14:18:24
