"use strict";
class Primitives {
	constructor(x = 7) {
            /* no super class */;
            this.string = "alpha" + x;
            this.bt = x % 2 === 0;
            this.bf = !this.bt;
            this.bite = x;
            this.car = x;
            this.shrt = 100 * x;
            this.loooong = 2147483647 * x;
            this.duble = 1.2 * x;
            this.f = 1.2 * x;
            this.i = x;
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Primitives";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = Primitives;
// Generated by JJJRMI 0.6.3
// 20.02.14 16:37:19
