"use strict";
const Primitives = require("./Primitives");
class PrimitivesExtended extends Primitives {
	constructor(i = 7) {
            super(i);
            this.__init();
            this.foo();
            PrimitivesExtended.bar();
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.PrimitivesExtended";
        }
	static __isEnum() {
            return false;
        }
	__init() {
            this.innerPrim = undefined;
        }
	static bar() {}
	foo() {}
};

if (typeof module !== "undefined") module.exports = PrimitivesExtended;
// Generated by JJJRMI 0.6.3
// 20.02.22 21:46:12
