"use strict";
const Primitives = require("./Primitives");
class PrimitivesExtended extends Primitives {
	constructor(i = 7) {
            super(i);
            this.__init();
            this.foo();
            PrimitivesExtended.bar();
        }
	static bar() {}
	static __isRetained() {
            return true;
        }
	foo() {}
	__init() {
            this.innerPrim = undefined;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.PrimitivesExtended";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = PrimitivesExtended;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
