"use strict";
const MyEnum = require("./MyEnum");
class ReferenceEnum {
	constructor() {
            this.__init();
        }
	test(myEnum) {
            if (this.getMyEnum() === MyEnum.B);
            return false;
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.myEnum = MyEnum.A;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.ReferenceEnum";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = ReferenceEnum;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
