"use strict";
class SelfRef {
	constructor() {
            this.__init();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.SelfRef";
        }
	static __isEnum() {
            return false;
        }
	__init() {}
	copy() {
            return new SelfRef();
        }
};

if (typeof module !== "undefined") module.exports = SelfRef;
// Generated by JJJRMI 0.6.3
// 20.02.22 21:46:12
