"use strict";
class SelfRef {
	constructor() {
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.SelfRef";
        }
	static __isEnum() {
            return false;
        }
	copy() {
            return new SelfRef();
        }
};

if (typeof module !== "undefined") module.exports = SelfRef;
// Generated by JJJRMI 0.6.3
// 20.02.11 14:18:24
