"use strict";
class SelfRef {
	constructor() {
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {}
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.SelfRef";
        }
	static __isHandler() {
            return false;
        }
	copy() {
            return new SelfRef();
        }
};

if (typeof module !== "undefined") module.exports = SelfRef;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
