"use strict";
class Shapes {
	constructor(value) {
            this.__value = value;
        }
	static __isRetained() {
            return true;
        }
	static __isTransient() {
            return true;
        }
	static __isEnum() {
            return true;
        }
	toString() {
            return this.__value;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Shapes";
        }
	static __isHandler() {
            return false;
        }
};
Shapes.valueArray = [];
Shapes.valueArray.push(Shapes.CIRCLE = new Shapes("CIRCLE"));
Shapes.valueArray.push(Shapes.SQUARE = new Shapes("SQUARE"));
Shapes.valueArray.push(Shapes.TRIANGLE = new Shapes("TRIANGLE"));
Shapes.values = function(){return Shapes.valueArray;};

if (typeof module !== "undefined") module.exports = Shapes;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
