"use strict";
class Simple {
	constructor() {
            this.x = 5;
            this.y = 7;
            this.shape = Shapes.CIRCLE;
            
        }
	static __isTransient() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Simple";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = Simple;
// Generated by JJJRMI 0.6.3
// 20.02.11 14:18:24
