"use strict";
const Shapes = require("./Shapes");
class Simple {
	constructor() {
            this.__init();
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.x = 5;
            this.y = 7;
            this.shape = Shapes.CIRCLE;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.Simple";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = Simple;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
