"use strict";
const Shapes = require("./Shapes");
class SimpleConst {
	constructor() {
            this.__init();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.SimpleConst";
        }
	static __isEnum() {
            return false;
        }
	__init() {
            this.x = 5;
            this.y = 7;
            this.shape = Shapes.CIRCLE;
        }
};

if (typeof module !== "undefined") module.exports = SimpleConst;
// Generated by JJJRMI 0.6.3
// 20.02.19 10:31:26
