"use strict";
const ArrayList = require("./ArrayList");
class UnknownNonJJJ {
	constructor() {
            this.array = new ArrayList();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.UnknownNonJJJ";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = UnknownNonJJJ;
// Generated by JJJRMI 0.6.3
// 20.02.17 17:01:26
