"use strict";
const ArrayList = require("../ext/ArrayList");
class UnknownNonJJJ {
	constructor() {
            this.__init();
            this.array = new ArrayList();
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.array = undefined;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.UnknownNonJJJ";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = UnknownNonJJJ;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
