"use strict";
class UnknownInternal {
	constructor() {
            this.__init();
            this.nonjjj = new NonJJJ();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.UnknownInternal";
        }
	static __isEnum() {
            return false;
        }
	__init() {
            this.nonjjj = undefined;
        }
};

if (typeof module !== "undefined") module.exports = UnknownInternal;
// Generated by JJJRMI 0.6.3
// 20.02.22 21:46:12
