"use strict";
const NonJJJ = require("./NonJJJ");
class UnknownInternal {
	constructor() {
            this.nonjjj = new NonJJJ();
        }
	static __isTransient() {
            return true;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.UnknownInternal";
        }
	static __isEnum() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = UnknownInternal;
// Generated by JJJRMI 0.6.3
// 20.02.17 17:24:26
