"use strict";
class UnknownInternal {
	constructor() {
            this.__init();
            this.nonjjj = new NonJJJ();
        }
	static __isRetained() {
            return true;
        }
	__init() {
            this.nonjjj = undefined;
        }
	static __isEnum() {
            return false;
        }
	static __getClass() {
            return "ca.frar.jjjrmi.testclasses.UnknownInternal";
        }
	static __isHandler() {
            return false;
        }
};

if (typeof module !== "undefined") module.exports = UnknownInternal;
// Generated by JJJRMI 0.7.0
// 20.04.02 15:24:11
